language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 edge: true
 local_dir: dist
 on:
   branch: master

default: &default
  source_path: app/javascript
  #source_entry_path: ./
  public_root_path: dist
  public_output_path: dist